### ISSUE TITLE
IDE internal errors

### ISSUE THREAD

**Issue by oguilleux** [biomejs/biome-intellij#25]
Hi I installed nightly v1.0.0 and using biome v1.5.1

and I get these errors : 

```
java.lang.Throwable: Biome failed to format the file
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.github.biomejs.intellijbiome.actions.OnSaveHelper.applyChanges(OnSaveHelper.kt:74)
	at com.github.biomejs.intellijbiome.actions.OnSaveHelper.access$applyChanges(OnSaveHelper.kt:16)
	at com.github.biomejs.intellijbiome.actions.OnSaveHelper$formatDocuments$1$1.run(OnSaveHelper.kt:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

My javascript file is just a test file like so : 

```
class General {
	constructor() {
		this.testVariable = 'script working';
		this.init();
	}

	init() {
		// for tests purposes only
		console.log(this.testVariable);
	}

	testing() {
		// for tests purposes only
		console.log('testing');

		  console.log('testing')




		// here is me commt

		console.log('testing');
	}

	newFunction() {
		// for tests purposes only
		console.log('testing');
	}
}

export default General;
```

**Comment by oguilleux** [comment]
I'll be glad to help you for reproduction. We can google meet if you want to see the problem.

**Comment by ematipico** [comment]
@oguilleux 

We don't require to see the issue, we require to **reproduce** issue on other machines, to make sure that the issue is consistent.

Please provide us with a snippet or a repository we can use

**Comment by oguilleux** [comment]
@ematipico sur here is it is : https://github.com/oguilleux/vite-wordpress-starter-theme

**Comment by victor-teles** [comment]
@oguilleux Thank you for the repository! I managed to reproduce the problem:

I received this error:

```
{exitCode=null, timeout=false, cancelled=false, stdout=, stderr=/Users/victormesquita/Documents/Projects/vite-wordpress-starter-theme/assets/src/js/_general.js internalError/fs ━━━━━━━━━━

  ! The file /Users/victormesquita/Documents/Projects/vite-wordpress-starter-theme/assets/src/js/_general.js was ignored.
}
```

You need to change how your project includes the files:

**from**
```
  "files": {
    "include": ["./assets/src/js"]
  },
```

**to**

**Comment by oguilleux** [comment]
new errors with latest v1.0.0-nightly.c0e49bc
updated my biome.json and simplified it : https://github.com/oguilleux/vite-wordpress-starter-theme

```java
java.lang.Throwable: Failed to run Biome check with (format) for file _general.js
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.github.biomejs.intellijbiome.actions.BiomeCheckRunner.applyChanges(BiomeCheckRunner.kt:91)
	at com.github.biomejs.intellijbiome.actions.BiomeCheckRunner.access$applyChanges(BiomeCheckRunner.kt:20)
	at com.github.biomejs.intellijbiome.actions.BiomeCheckRunner$formatDocuments$1$1.run(BiomeCheckRunner.kt:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by victor-teles** [comment]
@oguilleux I am not able to reproduce the same error (managed to reproduce a different one 😅 with ignored files)

I am releasing a new nightly version with some log improvements, this should help us understand the problem better

**Comment by oguilleux** [comment]
@victor-teles thanks a lot for taking time to debug this

new errors with v1.0.0-nightly.14eb397

```java
java.lang.Throwable: Failed to run Biome check with (format) for file _general.js - /vite-wordpress-starter-theme/biome.json/rome.json internalError/fs ━━━━━━━━━━

  × Biome couldn't read the file
  
  × Biome couldn't read the following file, maybe for permissions reasons or it doesn't exists: /vite-wordpress-starter-theme/biome.json/rome.json
  


	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.github.biomejs.intellijbiome.actions.BiomeCheckRunner.applyChanges(BiomeCheckRunner.kt:91)
	at com.github.biomejs.intellijbiome.actions.BiomeCheckRunner.access$applyChanges(BiomeCheckRunner.kt:20)
	at com.github.biomejs.intellijbiome.actions.BiomeCheckRunner$formatDocuments$1$1.run(BiomeCheckRunner.kt:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by ematipico** [comment]
It seems you're passing a path that contains the file `biome.json` at the end, did you see the log?

When passing a custom path, you need to pass the FOLDER where the configuration file is. Biome will look for the file `biome.json`

**Comment by oguilleux** [comment]
I'm not passing any paths personnally. 

I just check in the phpstorm > settings > tools > actions on save > Run Biome Check.

Then in my javascript hit CTRL + S

**Comment by ematipico** [comment]
@victor-teles you might want to look at this.

**Comment by victor-teles** [comment]
@oguilleux Which configuration mode are you using? I managed to reproduce the same error but only with manual mode by setting a custom biome.json path.

If you are using manual mode, please check if the [config path is a valid directory](https://github.com/biomejs/biome-intellij/issues/5):

<img src="https://github.com/biomejs/biome-intellij/assets/78874691/517ce55f-8421-48ff-baca-5fd1c26132d6" height="400"/>

**Comment by oguilleux** [comment]
Hi @victor-teles, it works !

after making the changes with directory instead of files. What was confusing though is that I was in automatic configuration and that it didn't work then changing to manual and setting the directory instead of the file solved the problem. Now when I switch back to automatic it works as well. Are you sure automatic is automatic ? 😄

**Comment by victor-teles** [comment]
@oguilleux Glad it worked.
I'll investigate the bug around configuration mode, thank you for the extra details.

About the UX, I think we can support both file and directory!
I'll close this issue and work on this UX improvement in #5
