### ISSUE TITLE
biome try to find rome.js

### ISSUE THREAD

**Issue by LoveMeWithoutAll** [biomejs/biome-intellij#36]
## Describe the bug
Biome CLI try to find the old `rome.json` file!
Of course, I only have `biome.json` file for setting

## Version
biome: [1.0.0-nightly.14eb397](https://plugins.jetbrains.com/plugin/22761-biome/versions/nightly/468749)

### webstorm
```
WebStorm 2023.3.3
Build #WS-233.14015.89, built on January 23, 2024
Licensed to 11Street Co., Ltd / YOUNGSEON AHN
Subscription is active until November 12, 2024.
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  Key Promoter X (2023.3.0)
  com.github.copilot (1.4.14.4554)
  com.github.biomejs.intellijbiome (1.0.0-nightly.14eb397)
  com.haulmont.rcb (233.13135.65)
  com.nekofar.milad.intellij.nuxtjs (2.0.10)
  aws.toolkit (2.7-233)
  izhangzhihao.rainbow.brackets (2024.2.1)
```

## Environment information
```sh
  System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 106.52 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    Yarn: 3.5.0 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.3.1 - /opt/homebrew/bin/pnpm
    bun: 1.0.26 - ~/.bun/bin/bun
  Browsers:
    Chrome: 121.0.6167.160
    Edge: 120.0.2210.144
    Safari: 17.3.1
    Safari Technology Preview: 17.4
```

## Logs

```java
java.lang.Throwable: Failed to run Biome check with (format, safefixes) for file HttpClientTest.tsx - /Users/a1101586/dev/11st/kitties-game-mw/biome.json/rome.json internalError/fs ━━━━━━━━━━━━━━━━━━━━━

  × Biome couldn't read the file
  
  × Biome couldn't read the following file, maybe for permissions reasons or it doesn't exists: /Users/a1101586/dev/11st/kitties-game-mw/biome.json/rome.json
  


	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.github.biomejs.intellijbiome.actions.BiomeCheckRunner.applyChanges(BiomeCheckRunner.kt:91)
	at com.github.biomejs.intellijbiome.actions.BiomeCheckRunner.access$applyChanges(BiomeCheckRunner.kt:20)
	at com.github.biomejs.intellijbiome.actions.BiomeCheckRunner$formatDocuments$1$1.run(BiomeCheckRunner.kt:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by ematipico** [comment]
In your configuration, you probably set a path to a `biome.json` file. You don't need to do that; just use the **folder**, and Biome will pick up `biome.json` by itself.

**Comment by LoveMeWithoutAll** [comment]
it works.
Thank you!
