### ISSUE TITLE
🐛 Intellij plugin keeps crashing

### ISSUE THREAD

**Issue by kubijo** [biomejs/biome-intellij#39]
## `biome rage`

```
CLI:
  Version:                      1.6.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.5.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/4.1.1"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

## Intellij crash report

```
Unhandled exception in [CoroutineName(ProjectImpl@1115438054 container), ProjectImpl@1115438054 container, StandaloneCoroutine{Cancelling}@335c30a, Dispatchers.Default]

com.intellij.execution.ExecutionException: Specify a valid package manager: cannot find a binary file inside '/~/.virtualenvs/xxx/bin/yarn' directory
	at com.intellij.javascript.nodejs.npm.NpmUtil.findBinCliFile(NpmUtil.java:178)
	at com.intellij.javascript.nodejs.npm.NpmUtil.getValidNpmCliJsFilePath(NpmUtil.java:103)
	at com.intellij.javascript.nodejs.interpreter.NodeCommandLineConfigurator.configure(NodeCommandLineConfigurator.java:37)
	at com.github.biomejs.intellijbiome.BiomeUtils.createNodeCommandLine(BiomeUtils.kt:80)
	at com.github.biomejs.intellijbiome.BiomeUtils.getBiomeVersion(BiomeUtils.kt:31)
	at com.github.biomejs.intellijbiome.widgets.BiomeWidget.getSelectedValue$lambda$0(BiomeWidget.kt:55)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:258)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:518)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(ProjectImpl@1115438054 container), ProjectImpl@1115438054 container, StandaloneCoroutine{Cancelled}@335c30a, Dispatchers.Default]
```

## Biome config dialog
- **Biome CLI Path**: `~/xxx/.yarn/unplugged/@biomejs-cli-linux-x64-npm-1.6.0-e1cc077d38/node_modules/@biomejs/cli-linux-x64/biome`
- **biome.json Directory Path**: `~/xxx/biome.json`

### What happened?

1. opened IDE
2. Saw a crash report

### Expected result

Working plugin.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
I don't think we support yarn

**Comment by michal-murawski** [comment]
Hi! To be sure, that's all the answer? 🤔 Any information, clue, etc., because yarn is pretty popular in the frontend world 🥲

**Comment by ematipico** [comment]
The version 1.0.0 should work with yarn, although I ma not totally sure.

**Comment by kubijo** [comment]
It also seems like a thing that has to be solved many times for other tools... Say eslint. And to mirror the sentiment of the previous poster, that reaction rubs a little on the flippant side.

To try to be a little more productive and helpful though... I could perhaps offer some of my time in addition to the monetary support to move this along. Also the main yarn architect was always extremely helpful to all the communities around.

**Comment by denbezrukov** [comment]
@kubijo 
Could you try please to use the night build?
https://plugins.jetbrains.com/plugin/22761-biome/versions/nightly

**Comment by kubijo** [comment]
> @kubijo Could you try please to use the night build? https://plugins.jetbrains.com/plugin/22761-biome/versions/nightly

I just installed `1.5.2-nightly.2bfccaf` and will be keeping an eye out for crashes.
For what it's worth, I re-enabled the extension some days ago, and it was "working" now ... in that it kept crashing the server somewhat, but not blocking the whole IDE.

**Comment by kubijo** [comment]
@denbezrukov Is it normal that the nightly seemingly started ignoring my config?

![image](https://github.com/user-attachments/assets/fca27fcf-168f-4eee-89ff-0493b825bd17)

**Comment by denbezrukov** [comment]
@kubijo I don't think so..
however I can't reproduce it 🤔
