### ISSUE TITLE
Plugin crashes in forever loop with `WorkingDirectoryNotFoundException`

### ISSUE THREAD

**Issue by ar4hc** [biomejs/biome-intellij#60]
i got one error stating
```
com.intellij.execution.WorkingDirectoryNotFoundException: Cannot start process, the working directory '' does not exist
```

in Intellij on Mac it's configured manually with
biome binary set to `/opt/homebrew/Cellar/biome/1.7.3/bin/biome` (brew installed binary)
and json path explicit set to the existing biome.json, which is working in another project.

CLI works fine, just Intellij has this forever crash.
also the lsp starts without complains from the shell (not a good test, but...).

Probably a config setting somewhere, but i found nowhere i can set this.

And perhaps don't restart forever on failure?

Complete stack trace from idea.log:
```
WARN - #c.i.p.l.i.LspServerImpl - BiomeLspServerDescriptor@****(Initializing;0): Failed to start LSP server
com.intellij.execution.WorkingDirectoryNotFoundException: Cannot start process, the working directory '' does not exist
	at com.intellij.execution.configurations.GeneralCommandLine.validateAndPrepareCommandLineForLocalRun(GeneralCommandLine.java:400)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:350)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:86)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:46)
	at com.intellij.platform.lsp.api.LspServerDescriptor$startServerProcess$1.<init>(LspServerDescriptor.kt:98)
	at com.intellij.platform.lsp.api.LspServerDescriptor.startServerProcess(LspServerDescriptor.kt:98)
	at com.intellij.platform.lsp.impl.connector.Lsp4jServerConnectorStdio.<init>(Lsp4jServerConnectorStdio.kt:17)
	at com.intellij.platform.lsp.impl.LspServerImpl.j(LspServerImpl.kt:318)
	at com.intellij.platform.lsp.impl.LspServerImpl.j(LspServerImpl.kt:298)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

biome rage:
```
CLI:
  Version:                      1.7.3
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           unset
  JS_RUNTIME_NAME:              unset
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

**Comment by siketyan** [comment]
This is already fixed in the main branch and will be released in the next version.
