### ISSUE TITLE
IntelliJ complains about errors in configuration file

### ISSUE THREAD

**Issue by zakius** [biomejs/biome-intellij#72]
Every time enable Biome in IntelliJ it pops up and no suggestions appear in the editor
```
Biome: The configuration file has errors. Biome will report only parsing errors until the configuration is fixed.
```

```
CLI:
  Version:                      1.8.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v21.6.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0


```
Biome plugin version 1.2.1 and IntelliJ version 2024.1.4

**Comment by ematipico** [comment]
Can you please give us more information? The warning is clear enough, your configuration file has errors. Why is this an issue?

E.g.: provide the configuration file, provide a playground link, etc.

**Comment by zakius** [comment]
that's an issue because the file is fine and CLI confirms that, it seems I missed that in my original post, sorry for that

to be fair it magically stopped showing that message after rebooting my PC and now it seems IntelliJ formats according to my settings but it is extremely slow to index, list files in the project tree, analyze files and when it finally finishes that shows no errors in the editor while CLI does print quite a lot of them

I don't know how I can help diagnosing it further, don't think the config file is the issue here but here it is in case it hints at something
```
{
    "$schema": "https://biomejs.dev/schemas/1.8.3/schema.json",
    "organizeImports": {
        "enabled": true
    },
    "formatter": {
        "enabled": true,
        "indentStyle": "space"
    },
    "linter": {
        "enabled": true,
        "rules": {
            "recommended": true
        }
    },
    "overrides": [
        {
            "include": [
                "*.svelte"
            ],
            "linter": {
                "rules": {
                    "style": {
                        "useConst": "off",
                        "useImportType": "off"
                    }
                }
            }
        }
    ],
    "vcs": {
        "enabled": true,
        "clientKind": "git",
        "useIgnoreFile": true
    },
    "files": {
        "include": [
            "src/**/*.ts",
            "src/**/*.svelte"
        ],
        "ignore": [
            ".idea",
            ".svelte-kit",
            "node_modules",
            "build"
        ]
    }
}

```

additionally it just works in vsc

**Comment by hrishikesh-k** [comment]
Facing the same issue. My project: https://github.com/hrishikesh-k/tejal/tree/v9 (v9 branch).

**Comment by terebentina** [comment]
Same problem here:
![image](https://github.com/user-attachments/assets/428b57c6-0c18-4cb0-98c2-265cb3a6508c)

But I think that error is masking the actual error which might be that biome can't actually read the file at all.
Can this be due to the file being in wsl? Is that $ sign or double slash tripping biome?
Here's the error I get when I make changes to biome.json:

```
java.lang.Throwable: Failed to run Biome check with (format, safefixes) for file biome.json - //wsl$/Ubuntu-24.04/home/dan/www/cust/wt/microservices/biome.json internalError/fs ━━━━━━━━━━━━━━━━━

  × Cannot read file
  
  × Biome can't read the following file, maybe for permissions reasons or it doesn't exist: //wsl$/Ubuntu-24.04/home/dan/www/cust/wt/microservices/biome.json
  


	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.github.biomejs.intellijbiome.actions.BiomeCheckRunner.applyChanges(BiomeCheckRunner.kt:105)
	at com.github.biomejs.intellijbiome.actions.BiomeCheckRunner.access$applyChanges(BiomeCheckRunner.kt:21)
	at com.github.biomejs.intellijbiome.actions.BiomeCheckRunner$formatDocuments$1$1.run(BiomeCheckRunner.kt:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:491)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$7(CoreProgressManager.java:542)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:502)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:467)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:463)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

My `biome.json` file in the root is more complex but I trimmed it down to try and narrow down the problem to just the below and I still have the same issue:
```
{
	"$schema": "https://biomejs.dev/schemas/1.9.2/schema.json",
	"vcs": { "enabled": true, "clientKind": "git", "useIgnoreFile": false },
	"files": { "ignoreUnknown": false, "ignore": [] },
	"formatter": {
		"enabled": true
	}
}
```
