### ISSUE TITLE
biome server bugs out on config, CLI works with the same.

### ISSUE THREAD

**Issue by LaravelFreelancerNL** [biomejs/biome-intellij#83]
I've got Biome setup with PhpStorm. It works perfectly fine from the commandline. 
However the 'integrated server' fails for automated fixes with the following error on startup:

"Biome: The configuration file has errors. Biome will report only parsing errors until the configuration is fixed."

System: W11 with WSL2-ubuntu
PhpStorm: 2024.2.0.1
Biome: 1.8.3

Devdependencies:
        "@biomejs/biome": "1.8.3",
        "@biomejs/cli-linux-x64": "^1.8.3",
        "@biomejs/cli-win32-x64": "^1.8.3",

PhpStorm Biome settings:
+ Automatic Biome configuration
+ Run biome for files: **/*.{js,mjs,mts,cjs,ts,jsx,tsx,cts,json,jsonc,vue,svelte,astro,css}
+ Run format on save.
+ Run safe fixes on save

biome.json in root of the project
```
{
    "$schema": "https://biomejs.dev/schemas/1.8.3/schema.json",
    "formatter": {
        "indentStyle": "space",
        "indentWidth": 4,
        "lineWidth": 120
    },
    "linter": {
        "ignore": ["assets", "core", "layouts", "tests", "types"]
    },
    "vcs": {
        "defaultBranch": "master",
        "clientKind": "git",
        "enabled": true,
        "useIgnoreFile": true
    }
}
```

I don't see anything wrong with this config and running biome format/lint through the CLI works perfectly fine with these settings.

Am I doing something wrong or have I stumbled upon a bug?

With kind regards
Bas.

**Comment by ematipico** [comment]
Can you provide a reproduction?

**Comment by LaravelFreelancerNL** [comment]
What do you mean by a reproduction in this sense?
These are the exact settings that I'm using and think might be relevant, are you missing anything specific?

The jetbrains plugin fails, the CLI works with these settings (within the same project).

**Comment by ematipico** [comment]
With minimal reproduction, I mean the minimal project (repository) where you can reproduce the issue consistently. I have a project very similar to yours, and I don't encounter the issue.

That's why it's important to have a brand you project, because it's possible that there are user settings that might interfere with  the project

**Comment by LaravelFreelancerNL** [comment]
Sure, I'll set one up over the weekend.

**Comment by Richard87** [comment]
Hi, I think i have the same issue, pretty sure it has something to do with WSL and the LSP server, I have the exact same issue in vscode

```
java.lang.Throwable: Failed to run Biome check with (format, safefixes, unsafefixes) for file biome.json - //wsl.localhost/Ubuntu/home/richard/projects/projectX/biome.json internalError/fs ━━━━━━━━━━

  × Cannot read file
  
  × Biome can't read the following file, maybe for permissions reasons or it doesn't exist: //wsl.localhost/Ubuntu/home/richard/projects/projectX/biome.json
  


	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.github.biomejs.intellijbiome.actions.BiomeCheckRunner.applyChanges(BiomeCheckRunner.kt:91)
	at com.github.biomejs.intellijbiome.actions.BiomeCheckRunner.access$applyChanges(BiomeCheckRunner.kt:20)
	at com.github.biomejs.intellijbiome.actions.BiomeCheckRunner$formatDocuments$1$1.run(BiomeCheckRunner.kt:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:49)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:501)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:466)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:97)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:92)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:464)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by LaravelFreelancerNL** [comment]
I can confirm there is some kind of interference from the project itself. I haven't had time to dig deeper than a superficial check.
t.b.c.

**Comment by kbytesys** [comment]
This bug is related to the lack of support to wsl. there are other 2 bugs related to the same error.

I don't know if maintainers are planning some kind of support since we are reporting the same problem time by time :p

**Comment by Richard87** [comment]
For the record, the fix I posted in the other thread does work nicely for me:
- `winget install "Node.js"` 
- possibly restart your terminal
- Install biome on the hots (`npm install -g @biomejs/biome`) 
- Manually specify Biome in intellij config: `C:\Users\USERNAME\AppData\Roaming\npm\biome.cmd`

**Comment by kbytesys** [comment]
But this is not a fix, because you are using WSL to avoid to install software in your host (in some company laptops you can't install what you want). The real fix is to use the executable inside WSL.

**Comment by dualsoftax** [comment]
Same issue here, any update on this one?

**Comment by ematipico** [comment]
The issue still lacks a reproduction, which was requested months ago.

**Comment by dualsoftax** [comment]
I will describe my setup and how to reproduce this:

OS: Windows 10/11
WSL2 linux 24.04
Node 22lts (installed in WSL)
pnpm v10 package manager

I am using latest version of biomejs in my project inside wsl2 and Webstorm as IDE. In webstorm settings I have configured that Node.js interpreter is pulled from WSL Ubuntu as well as package manager pnpm. All other plugins like tailwind, typescript, eslint, prettier work fine and read executable from WSL, except biomejs reporting same issue as described here on top.


```
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "\\wsl.localhost\Ubuntu-24.04\home\ax\code\test\node_modules\@biomejs\biome\bin\biome" (in directory "\\wsl.localhost\Ubuntu-24.04\home\ax\code\test"): CreateProcess error=2, The system cannot find the file specified
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:384)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:21)
	at com.github.biomejs.intellijbiome.GeneralProcessCommandBuilder$build$4.<init>(GeneralProcessCommandBuilder.kt:55)
	at com.github.biomejs.intellijbiome.GeneralProcessCommandBuilder.build(GeneralProcessCommandBuilder.kt:55)
	at com.github.biomejs.intellijbiome.lsp.BiomeLspServerDescriptor.startServerProcess(BiomeLspServerSupportProvider.kt:70)
	at com.intellij.platform.lsp.impl.connector.Lsp4jServerConnectorStdio.<init>(Lsp4jServerConnectorStdio.kt:16)
	at com.intellij.platform.lsp.impl.LspServerImpl.Q(LspServerImpl.kt:387)
	at com.intellij.platform.lsp.impl.LspServerImpl.Q(LspServerImpl.kt:354)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport$executeOnPooledThread$1.run(AnyThreadWriteThreadingSupport.kt:167)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.intellij.util.concurrency.ContextCallable.lambda$call$1(ContextCallable.java:74)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:83)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: Cannot run program "\\wsl.localhost\Ubuntu-24.04\home\ax\code\test\node_modules\@biomejs\biome\bin\biome" (in directory "\\wsl.localhost\Ubuntu-24.04\home\ax\code\test"): CreateProcess error=2, The system cannot find the file specified

```

**Comment by dualsoftax** [comment]
`java.lang.IllegalStateException: There is no ProgressIndicator or Job in this thread, the current job is not cancellable.
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable$lambda$0(coroutines.kt:142)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:85)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:140)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:123)
	at com.intellij.execution.wsl.WslIjentUtil.runProcessBlocking(WslIjentUtil.kt:68)
	at com.intellij.execution.wsl.WSLDistribution.lambda$patchCommandLine$2(WSLDistribution.java:245)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:463)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:469)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:374)
	at com.intellij.execution.wsl.target.WslTargetEnvironment.createProcess(WslTargetEnvironment.kt:129)
	at com.intellij.javascript.nodejs.execution.NodeTargetRun.startProcessEx(NodeTargetRun.kt:183)
	at com.github.biomejs.intellijbiome.NodeProcessCommandBuilder.build(NodeProcessCommandBuilder.kt:60)
	at com.github.biomejs.intellijbiome.lsp.BiomeLspServerDescriptor.startServerProcess(BiomeLspServerSupportProvider.kt:71)
	at com.intellij.platform.lsp.impl.connector.Lsp4jServerConnectorStdio.<init>(Lsp4jServerConnectorStdio.kt:16)
	at com.intellij.platform.lsp.impl.LspServerImpl.Q(LspServerImpl.kt:387)
	at com.intellij.platform.lsp.impl.LspServerImpl.Q(LspServerImpl.kt:354)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport$executeOnPooledThread$1.run(AnyThreadWriteThreadingSupport.kt:167)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.intellij.util.concurrency.ContextCallable.lambda$call$1(ContextCallable.java:74)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:83)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
`

**Comment by pxDot** [comment]
@denbezrukov still the same error (same logs as in https://github.com/biomejs/biome-intellij/issues/83#issuecomment-2642395125) for me with the latest nightly version.
